on: [push]

jobs:
  create_issues_actions:
     runs-on: ubuntu-latest
     name: create auto issues actions
     steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: create_issues_actions
          uses: ./

          with:
            token: ${{secrets.ACTIONS_DEMO_TOKEN}}
        
