on:
  schedule:
    // 13:55
    // UTC 中国时区 -8 （13-8 = 5）
    - cron:  '59 5 * * *'

jobs:
  create_issues_actions:
     runs-on: ubuntu-latest
     name: create auto issues actions
     steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: create issues actions
          uses: ./

          with:
            tokens: ${{secrets.ACTIONS_DEMO_TOKEN}}
        
