
name: Update-Demo

# on: [push]
on:
  schedule:
    # 11:35  11-8
    - cron:  '*/20 * * * *'

jobs:
  create-issues-actions:
     runs-on: ubuntu-latest
     name: create-issues-actions
     steps:
        - name: Checkout
          uses: actions/checkout@v2
          # run: echo "下载成功"
          
        - name: create issues actions
          uses: ./

          with:
            tokens: ${{secrets.ACTIONS_DEMO_TOKEN}}
        
